const fs = require('fs');
const path = require('path');
const logger = require('../utils/logger');

const OUTPUT_DIR = path.join(__dirname, '../../generated');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function writeFile(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
}

function generateExpressApp(name) {
  const dir = path.join(OUTPUT_DIR, name);
  ensureDir(dir);

  writeFile(path.join(dir, 'package.json'), JSON.stringify({
    name,
    version: '1.0.0',
    description: `Generated by Ibrabot`,
    main: 'index.js',
    scripts: { start: 'node index.js', dev: 'nodemon index.js' },
    dependencies: { express: '^4.18.0', dotenv: '^16.0.0', cors: '^2.8.5' }
  }, null, 2));

  writeFile(path.join(dir, '.env.example'), [
    'PORT=3000',
    'NODE_ENV=development'
  ].join('\n'));

  writeFile(path.join(dir, 'index.js'), `
require('dotenv').config();
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'API ${name} running', status: 'ok' });
});

app.get('/health', (req, res) => res.json({ status: 'ok', ts: Date.now() }));

app.listen(PORT, () => console.log(\`Server running on port \${PORT}\`));
`.trim());

  writeFile(path.join(dir, 'README.md'), `# ${name}\nGenerated by Ibrabot.\n\n## Start\n\`\`\`bash\nnpm install && npm start\n\`\`\``);

  logger.success('Express app scaffolded: ' + dir);
  return dir;
}

function generateReactApp(name) {
  const dir = path.join(OUTPUT_DIR, name);
  ensureDir(dir);

  writeFile(path.join(dir, 'package.json'), JSON.stringify({
    name,
    version: '0.1.0',
    private: true,
    scripts: {
      start: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: { react: '^18.0.0', 'react-dom': '^18.0.0' },
    devDependencies: { vite: '^5.0.0', '@vitejs/plugin-react': '^4.0.0' }
  }, null, 2));

  writeFile(path.join(dir, 'vite.config.js'), `
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
export default defineConfig({ plugins: [react()], server: { host: '0.0.0.0', port: 5000 } });
`.trim());

  writeFile(path.join(dir, 'index.html'), `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"/><title>${name}</title></head>
<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body>
</html>`);

  ensureDir(path.join(dir, 'src'));

  writeFile(path.join(dir, 'src/main.jsx'), `
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
createRoot(document.getElementById('root')).render(<App />);
`.trim());

  writeFile(path.join(dir, 'src/App.jsx'), `
import React from 'react';
export default function App() {
  return <div style={{padding:'2rem',fontFamily:'sans-serif'}}><h1>${name}</h1><p>Generated by Ibrabot.</p></div>;
}
`.trim());

  writeFile(path.join(dir, 'README.md'), `# ${name}\nGenerated by Ibrabot.\n\n## Start\n\`\`\`bash\nnpm install && npm start\n\`\`\``);

  logger.success('React app scaffolded: ' + dir);
  return dir;
}

function generateFullStack(name) {
  const apiDir = generateExpressApp(`${name}-api`);
  const uiDir = generateReactApp(`${name}-ui`);
  logger.success(`Fullstack ${name} scaffolded: API → ${apiDir} | UI → ${uiDir}`);
  return { api: apiDir, ui: uiDir };
}

function listGenerated() {
  if (!fs.existsSync(OUTPUT_DIR)) return [];
  return fs.readdirSync(OUTPUT_DIR);
}

module.exports = {
  generateExpressApp,
  generateReactApp,
  generateFullStack,
  listGenerated,
  OUTPUT_DIR
};
